---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            OUTPUT_CERTS: /tmp/istio-certs
        sidecar.istio.io/userVolume: '[{"name": "istio-certs", "emptyDir": {"medium": "Memory"}}]'
        sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/tmp/istio-certs"}]'
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: sleep
      containers:
        - name: sleep
          image: curlimages/curl
          command:
            - /bin/sleep
            - 3650d
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tmp/istio-certs/
              name: istio-certs
      volumes:
        - emptyDir: null
          name: istio-certs

