---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-v3
  labels:
    app: movies
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
      version: v3
  template:
    metadata:
      labels:
        app: movies
        version: v3
    spec:
      serviceAccountName: movies
      containers:
      - name: movies
        image: codesparks/examples-moviesuggestion-movies-v3:1.0
        env:
          - name: ACTORS_HOSTNAME
            value: "actors:8082"
        livenessProbe:
          initialDelaySeconds: 60 
          httpGet:
            path: /actuator/health
            port: 8081
        readinessProbe:
          httpGet:
            path: /movies/ready
            port: 8081
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
